/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    projects: Project;
    services: Service;
    testimonials: Testimonial;
    'faq-items': FaqItem;
    ctas: Cta;
    inquiries: Inquiry;
    machinery: Machinery;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    ctas: CtasSelect<false> | CtasSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    machinery: MachinerySelect<false> | MachinerySelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'business-info': BusinessInfo;
    navbar: Navbar;
    'home-page': HomePage;
  };
  globalsSelect: {
    'business-info': BusinessInfoSelect<false> | BusinessInfoSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required to read. Useful for building public pages.
   */
  allowPublicRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username?: string | null;
  firstName: string;
  lastName: string;
  address?: string | null;
  phoneNumber?: string | null;
  vatId?: string | null;
  companyName?: string | null;
  roles?: ('super-admin' | 'user')[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title if left blank)
   */
  slug?: string | null;
  /**
   * Detailed description of the project
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  projectStatus: 'planned' | 'in-progress' | 'completed';
  location?: string | null;
  metadata?: {
    startDate?: string | null;
    completionDate?: string | null;
    client?: string | null;
    /**
     * Optional budget information
     */
    budget?: string | null;
  };
  hasBeforeAfterPairs?: boolean | null;
  projectImages?:
    | {
        type: 'single' | 'comparison';
        image?: (number | null) | Media;
        imageAltText?: string | null;
        imageDescription?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Explain what changes are shown in this before/after comparison
         */
        comparisonDescription?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        beforeImage?: {
          image: number | Media;
          altText?: string | null;
        };
        afterImage?: {
          image: number | Media;
          altText?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Add relevant tags to categorize this project
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * ID se generira samodejno iz naslova.
   */
  serviceId?: string | null;
  title: string;
  description: string;
  features?:
    | {
        featureText: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mnenja strank o naših storitvah.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Relativni čas ali specifični datum podaje mnenja.
   */
  time?: string | null;
  location?: string | null;
  service?: string | null;
  content: string;
  /**
   * Ocena stranke od 1 do 5 zvezdic.
   */
  rating: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pogosta vprašanja in odgovori.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  tenant?: (number | null) | Tenant;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable Call-to-Action buttons.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctas".
 */
export interface Cta {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Besedilo, ki bo prikazano na gumbu.
   */
  ctaText: string;
  /**
   * Kam naj gumb vodi (npr. /kontakt, /#storitve, https://example.com).
   */
  ctaHref: string;
  /**
   * Dodaten CSS razred za stilsko oblikovanje gumba na spletni strani (npr. primary-button, secondary-button).
   */
  ctaClassname?: string | null;
  /**
   * Izberite stil gumba (npr. Primary, Secondary). To lahko vpliva na izgled gumba na spletni strani.
   */
  ctaType?: ('primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link' | 'icon') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  tenant?: (number | null) | Tenant;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  message: string;
  service: number | Service;
  location: string;
  status?: ('new' | 'in-progress' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Podatki o gradbeni mehanizaciji.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machinery".
 */
export interface Machinery {
  id: number;
  tenant?: (number | null) | Tenant;
  tabName: string;
  /**
   * Npr. Volvo EL70, Komatsu PC210
   */
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Dodajte ključne specifikacije.
   */
  specifications?:
    | {
        specName: string;
        specDetails: {
          detail: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Npr. Premik stroja na kolesih za krajše razdalje (do 40km)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'ctas';
        value: number | Cta;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'machinery';
        value: number | Machinery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  slug?: T;
  allowPublicRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  firstName?: T;
  lastName?: T;
  address?: T;
  phoneNumber?: T;
  vatId?: T;
  companyName?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  projectStatus?: T;
  location?: T;
  metadata?:
    | T
    | {
        startDate?: T;
        completionDate?: T;
        client?: T;
        budget?: T;
      };
  hasBeforeAfterPairs?: T;
  projectImages?:
    | T
    | {
        type?: T;
        image?: T;
        imageAltText?: T;
        imageDescription?: T;
        comparisonDescription?: T;
        beforeImage?:
          | T
          | {
              image?: T;
              altText?: T;
            };
        afterImage?:
          | T
          | {
              image?: T;
              altText?: T;
            };
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tenant?: T;
  serviceId?: T;
  title?: T;
  description?: T;
  features?:
    | T
    | {
        featureText?: T;
        id?: T;
      };
  image?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  time?: T;
  location?: T;
  service?: T;
  content?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  tenant?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctas_select".
 */
export interface CtasSelect<T extends boolean = true> {
  tenant?: T;
  ctaText?: T;
  ctaHref?: T;
  ctaClassname?: T;
  ctaType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  tenant?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  message?: T;
  service?: T;
  location?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machinery_select".
 */
export interface MachinerySelect<T extends boolean = true> {
  tenant?: T;
  tabName?: T;
  name?: T;
  description?: T;
  image?: T;
  specifications?:
    | T
    | {
        specName?: T;
        specDetails?:
          | T
          | {
              detail?: T;
              id?: T;
            };
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info".
 */
export interface BusinessInfo {
  id: number;
  /**
   * Polno ime podjetja.
   */
  companyName: string;
  companyAbout: string;
  vatId: string;
  businessId: string;
  registryDate: string;
  location: string;
  phoneNumber: string;
  email: string;
  facebookUrl?: string | null;
  googleReviewUrl?: string | null;
  /**
   * Temna varianta logotipa, ki se uporablja na svetlih ozadjih.
   */
  logo?: (number | null) | Media;
  /**
   * Svetla varianta logotipa, ki se uporablja na temnih ozadjih. Če ni izbrana, se uporabi temna varianta.
   */
  logoLight?: (number | null) | Media;
  /**
   * Dodajte povezave do vaših profilov na platformah za pridobivanje strank.
   */
  leadGenPlatformUrls?:
    | {
        platformName: 'Primerjam.si' | 'Omisli.si' | 'MojMojster.net';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Koordinate lokacije podjetja za prikaz na zemljevidu.
   */
  coordinates: {
    /**
     * Geografska širina lokacije podjetja.
     */
    latitude: number;
    /**
     * Geografska dolžina lokacije podjetja.
     */
    longitude: number;
  };
  /**
   * Radius v metrih, ki označuje območje kjer podjetje nudi svoje storitve.
   */
  serviceRadius: number;
  /**
   * Naslov, ki se prikaže v zavihku brskalnika in rezultatih iskanja.
   */
  metaTitle: string;
  /**
   * Kratek opis strani za rezultate iskanja (približno 155-160 znakov).
   */
  metaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  title?: string | null;
  navItems?:
    | {
        title: string;
        hasChildren?: boolean | null;
        /**
         * Vnesite ciljno pot, npr. /o-nas ali #kontakt.
         */
        href?: string | null;
        /**
         * Dodajte elemente za spustni meni.
         */
        children?:
          | {
              title: string;
              /**
               * Vnesite ciljno pot, npr. /storitve/rezanje-betona.
               */
              href: string;
              /**
               * Kratek opis, ki se prikaže v spustnem meniju.
               */
              description: string;
              /**
               * Izberite ikono, ki se prikaže ob elementu v spustnem meniju.
               */
              icon?: ('Sparkles' | 'Zap' | 'Drop' | 'Hands' | 'Footprints' | 'Paintbrush') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Izberite CTA gumb, ki bo prikazan v navigaciji.
   */
  mainCta?: (number | null) | Cta;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  heroHideSection?: boolean | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  /**
   * Izberite CTA gumbe za naslovno sekcijo. Vrstni red je pomemben.
   */
  heroCtas?: (number | Cta)[] | null;
  heroImage?: (number | null) | Media;
  heroFeatures?:
    | {
        iconText?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  servicesHideSection?: boolean | null;
  servicesTitle?: string | null;
  servicesDescription?: string | null;
  /**
   * Izberite storitve, ki se prikažejo na domači strani. Vrstni red je pomemben.
   */
  selectedServices?: (number | Service)[] | null;
  /**
   * Izberite CTA gumb za sekcijo Storitve (neobvezno).
   */
  servicesCta?: (number | null) | Cta;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  machineryHideSection?: boolean | null;
  machineryTitle?: string | null;
  machineryDescription?: string | null;
  /**
   * Izberite stroje, ki se prikažejo na domači strani. Vrstni red je pomemben.
   */
  selectedMachinery?: (number | Machinery)[] | null;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  projectsHideSection?: boolean | null;
  projectHighlightsTitle?: string | null;
  projectHighlightsDescription?: string | null;
  projectHighlightsButtonText?: string | null;
  projectHighlightsButtonHref?: string | null;
  /**
   * Izberite projekte, ki se prikažejo na domači strani. Priporočljivo 3-4 projekte.
   */
  highlightedProjects?: (number | Project)[] | null;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  aboutHideSection?: boolean | null;
  aboutTitle?: string | null;
  aboutDescription?: string | null;
  aboutImage?: (number | null) | Media;
  aboutBenefits?:
    | {
        /**
         * Interni ID, mora biti unikaten.
         */
        benefitId?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Izberite CTA gumb za sekcijo O nas (neobvezno).
   */
  aboutCta?: (number | null) | Cta;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  testimonialsHideSection?: boolean | null;
  testimonialsTitle?: string | null;
  /**
   * Izberite mnenja, ki se prikažejo na domači strani. Vrstni red je pomemben.
   */
  selectedTestimonials?: (number | Testimonial)[] | null;
  /**
   * Izberite CTA gumb za sekcijo Mnenja strank (neobvezno).
   */
  testimonialsCta?: (number | null) | Cta;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  galleryHideSection?: boolean | null;
  galleryTitle?: string | null;
  galleryDescription?: string | null;
  galleryButtonText?: string | null;
  /**
   * Izberite CTA gumb za galerijo (neobvezno).
   */
  galleryCta?: (number | null) | Cta;
  /**
   * Izberite slike iz medijske knjižnice, ki se prikažejo v galeriji na domači strani. Vrstni red je pomemben.
   */
  galleryImages?: (number | Media)[] | null;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  serviceAreaHideSection?: boolean | null;
  serviceAreaTitle?: string | null;
  serviceAreaDescription?: string | null;
  /**
   * Če je označeno, bo prikazan zemljevid. Preverite, ali so 'Koordinate sedeža' pravilno nastavljene v splošnih nastavitvah strani.
   */
  showMap?: boolean | null;
  serviceAreaLocations?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  serviceAreaAdditionalInfo?: string | null;
  /**
   * Izberite CTA gumb za kontaktno sekcijo (neobvezno).
   */
  contactCta?: (number | null) | Cta;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  contactHideSection?: boolean | null;
  contactTitle?: string | null;
  contactDescription?: string | null;
  contactWorkingHours?:
    | {
        day?: string | null;
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  contactPhoneNumber?: string | null;
  contactAddress?: string | null;
  /**
   * Če je označeno, ta sekcija ne bo prikazana na spletni strani.
   */
  faqHideSection?: boolean | null;
  faqTitle?: string | null;
  faqDescription?: string | null;
  faqDefaultOpenItem?: (number | null) | FaqItem;
  /**
   * Izberite pogosta vprašanja, ki se prikažejo na domači strani. Vrstni red je pomemben.
   */
  selectedFaqItems?: (number | FaqItem)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info_select".
 */
export interface BusinessInfoSelect<T extends boolean = true> {
  companyName?: T;
  companyAbout?: T;
  vatId?: T;
  businessId?: T;
  registryDate?: T;
  location?: T;
  phoneNumber?: T;
  email?: T;
  facebookUrl?: T;
  googleReviewUrl?: T;
  logo?: T;
  logoLight?: T;
  leadGenPlatformUrls?:
    | T
    | {
        platformName?: T;
        url?: T;
        id?: T;
      };
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  serviceRadius?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  title?: T;
  navItems?:
    | T
    | {
        title?: T;
        hasChildren?: T;
        href?: T;
        children?:
          | T
          | {
              title?: T;
              href?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  mainCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroHideSection?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroCtas?: T;
  heroImage?: T;
  heroFeatures?:
    | T
    | {
        iconText?: T;
        text?: T;
        id?: T;
      };
  servicesHideSection?: T;
  servicesTitle?: T;
  servicesDescription?: T;
  selectedServices?: T;
  servicesCta?: T;
  machineryHideSection?: T;
  machineryTitle?: T;
  machineryDescription?: T;
  selectedMachinery?: T;
  projectsHideSection?: T;
  projectHighlightsTitle?: T;
  projectHighlightsDescription?: T;
  projectHighlightsButtonText?: T;
  projectHighlightsButtonHref?: T;
  highlightedProjects?: T;
  aboutHideSection?: T;
  aboutTitle?: T;
  aboutDescription?: T;
  aboutImage?: T;
  aboutBenefits?:
    | T
    | {
        benefitId?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  aboutCta?: T;
  testimonialsHideSection?: T;
  testimonialsTitle?: T;
  selectedTestimonials?: T;
  testimonialsCta?: T;
  galleryHideSection?: T;
  galleryTitle?: T;
  galleryDescription?: T;
  galleryButtonText?: T;
  galleryCta?: T;
  galleryImages?: T;
  serviceAreaHideSection?: T;
  serviceAreaTitle?: T;
  serviceAreaDescription?: T;
  showMap?: T;
  serviceAreaLocations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  serviceAreaAdditionalInfo?: T;
  contactCta?: T;
  contactHideSection?: T;
  contactTitle?: T;
  contactDescription?: T;
  contactWorkingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  contactPhoneNumber?: T;
  contactAddress?: T;
  faqHideSection?: T;
  faqTitle?: T;
  faqDescription?: T;
  faqDefaultOpenItem?: T;
  selectedFaqItems?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}