/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    projects: Project;
    services: Service;
    testimonials: Testimonial;
    'faq-items': FaqItem;
    ctas: Cta;
    inquiries: Inquiry;
    machinery: Machinery;
    'opening-hours': OpeningHour;
    pages: Page;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    ctas: CtasSelect<false> | CtasSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    machinery: MachinerySelect<false> | MachinerySelect<true>;
    'opening-hours': OpeningHoursSelect<false> | OpeningHoursSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'business-info': BusinessInfo;
    navbar: Navbar;
    footer: Footer;
  };
  globalsSelect: {
    'business-info': BusinessInfoSelect<false> | BusinessInfoSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required to read. Useful for building public pages.
   */
  allowPublicRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username?: string | null;
  firstName: string;
  lastName: string;
  address?: string | null;
  phoneNumber?: string | null;
  vatId?: string | null;
  companyName?: string | null;
  roles?: ('super-admin' | 'user')[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug?: string | null;
  /**
   * Detailed description of the project
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  projectStatus: 'planned' | 'in-progress' | 'completed';
  location?: string | null;
  metadata?: {
    startDate?: string | null;
    completionDate?: string | null;
    client?: string | null;
    /**
     * Optional budget information
     */
    budget?: string | null;
  };
  hasBeforeAfterPairs?: boolean | null;
  projectImages?:
    | {
        type: 'single' | 'comparison';
        image?: (number | null) | Media;
        imageAltText?: string | null;
        imageDescription?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Explain what changes are shown in this before/after comparison
         */
        comparisonDescription?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        beforeImage?: {
          image: number | Media;
          altText?: string | null;
        };
        afterImage?: {
          image: number | Media;
          altText?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Add relevant tags to categorize this project
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * ID se generira samodejno iz naslova.
   */
  serviceId?: string | null;
  title: string;
  description: string;
  features?:
    | {
        featureText: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mnenja strank o naših storitvah.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Relativni čas ali specifični datum podaje mnenja.
   */
  time?: string | null;
  location?: string | null;
  service?: string | null;
  content: string;
  /**
   * Ocena stranke od 1 do 5 zvezdic.
   */
  rating: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pogosta vprašanja in odgovori.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  tenant?: (number | null) | Tenant;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable Call-to-Action buttons.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctas".
 */
export interface Cta {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Besedilo, ki bo prikazano na gumbu.
   */
  ctaText: string;
  /**
   * Kam naj gumb vodi (npr. /kontakt, /#storitve, https://example.com).
   */
  ctaHref: string;
  /**
   * Dodaten CSS razred za stilsko oblikovanje gumba na spletni strani (npr. primary-button, secondary-button).
   */
  ctaClassname?: string | null;
  /**
   * Izberite stil gumba (npr. Primary, Secondary). To lahko vpliva na izgled gumba na spletni strani.
   */
  ctaType?: ('primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link' | 'icon') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  tenant?: (number | null) | Tenant;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  message: string;
  service: number | Service;
  location: string;
  status?: ('new' | 'in-progress' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Podatki o gradbeni mehanizaciji.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machinery".
 */
export interface Machinery {
  id: number;
  tenant?: (number | null) | Tenant;
  tabName: string;
  /**
   * Npr. Volvo EL70, Komatsu PC210
   */
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Dodajte ključne specifikacije.
   */
  specifications?:
    | {
        specName: string;
        specDetails: {
          detail: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Npr. Premik stroja na kolesih za krajše razdalje (do 40km)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define different opening hours schedules (e.g., regular, seasonal, emergency).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-hours".
 */
export interface OpeningHour {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * E.g., "Regular Hours", "Summer Schedule", "Emergency On-Call"
   */
  name: string;
  /**
   * Optional. Schedule is active starting from this date.
   */
  startDate?: string | null;
  /**
   * Optional. Schedule is active until this date.
   */
  endDate?: string | null;
  dailyHours?:
    | {
        days: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
        timeSlots: {
          startTime: string;
          endTime: string;
          /**
           * Optional notes for this specific time slot (e.g., "Appointments only")
           */
          notes?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Optional general notes for the entire schedule.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  publishedAt?: string | null;
  slug?: string | null;
  layout?:
    | (
        | HeroBlock
        | ServicesBlock
        | ProjectHighlightsBlock
        | AboutBlock
        | TestimonialsBlock
        | GalleryBlock
        | ServiceAreaBlock
        | ContactBlock
        | FAQBlock
        | MachineryBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  template: 'default';
  title?: string | null;
  subtitle?: string | null;
  /**
   * Izberite CTA gumbe za naslovno sekcijo. Vrstni red je pomemben.
   */
  ctas?: (number | Cta)[] | null;
  image?: (number | null) | Media;
  features?:
    | {
        iconText?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  template: 'default';
  title?: string | null;
  description?: string | null;
  /**
   * Izberite storitve, ki se prikažejo na domači strani. Vrstni red je pomemben.
   */
  selectedServices?: (number | Service)[] | null;
  /**
   * Izberite CTA gumb za sekcijo Storitve (neobvezno).
   */
  serviceCta?: (number | null) | Cta;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectHighlightsBlock".
 */
export interface ProjectHighlightsBlock {
  template: 'default';
  title?: string | null;
  description?: string | null;
  buttonText?: string | null;
  buttonHref?: string | null;
  /**
   * Izberite projekte za prikaz na domači strani. Vrstni red je pomemben.
   */
  highlightedProjects?: (number | Project)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectHighlights';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  template: 'default';
  title?: string | null;
  description?: string | null;
  benefits?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Ime ikone (npr. Star, Trophy, Clock)
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  template: 'default';
  title?: string | null;
  description?: string | null;
  /**
   * Izberite mnenja strank, ki bodo prikazana na domači strani. Vrstni red je pomemben.
   */
  selectedTestimonials?: (number | Testimonial)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  template: 'default';
  title?: string | null;
  description?: string | null;
  galleryImages?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Izberite CTA gumb za galerijo (neobvezno).
   */
  galleryCta?: (number | null) | Cta;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceAreaBlock".
 */
export interface ServiceAreaBlock {
  template: 'default';
  title?: string | null;
  description?: string | null;
  showMap?: boolean | null;
  locations?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'serviceArea';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  template: 'default' | 'simple';
  title?: string | null;
  description?: string | null;
  /**
   * Select one or more opening hours schedules to display.
   */
  openingHoursSchedules?: (number | OpeningHour)[] | null;
  phoneNumber?: string | null;
  address?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  template: 'default';
  title?: string | null;
  description?: string | null;
  /**
   * Izberite vprašanja, ki bodo prikazana na domači strani. Vrstni red je pomemben.
   */
  selectedFaqs?: (number | FaqItem)[] | null;
  /**
   * Izberite CTA gumb za sekcijo FAQ (neobvezno).
   */
  faqCta?: (number | null) | Cta;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MachineryBlock".
 */
export interface MachineryBlock {
  title?: string | null;
  description?: string | null;
  /**
   * Izberite stroje, ki se prikažejo na domači strani. Vrstni red je pomemben.
   */
  selectedMachinery?: (number | Machinery)[] | null;
  template: 'default';
  id?: string | null;
  blockName?: string | null;
  blockType: 'machinery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'ctas';
        value: number | Cta;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'machinery';
        value: number | Machinery;
      } | null)
    | ({
        relationTo: 'opening-hours';
        value: number | OpeningHour;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  slug?: T;
  allowPublicRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  firstName?: T;
  lastName?: T;
  address?: T;
  phoneNumber?: T;
  vatId?: T;
  companyName?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  projectStatus?: T;
  location?: T;
  metadata?:
    | T
    | {
        startDate?: T;
        completionDate?: T;
        client?: T;
        budget?: T;
      };
  hasBeforeAfterPairs?: T;
  projectImages?:
    | T
    | {
        type?: T;
        image?: T;
        imageAltText?: T;
        imageDescription?: T;
        comparisonDescription?: T;
        beforeImage?:
          | T
          | {
              image?: T;
              altText?: T;
            };
        afterImage?:
          | T
          | {
              image?: T;
              altText?: T;
            };
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tenant?: T;
  serviceId?: T;
  title?: T;
  description?: T;
  features?:
    | T
    | {
        featureText?: T;
        id?: T;
      };
  image?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  time?: T;
  location?: T;
  service?: T;
  content?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  tenant?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctas_select".
 */
export interface CtasSelect<T extends boolean = true> {
  tenant?: T;
  ctaText?: T;
  ctaHref?: T;
  ctaClassname?: T;
  ctaType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  tenant?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  message?: T;
  service?: T;
  location?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machinery_select".
 */
export interface MachinerySelect<T extends boolean = true> {
  tenant?: T;
  tabName?: T;
  name?: T;
  description?: T;
  image?: T;
  specifications?:
    | T
    | {
        specName?: T;
        specDetails?:
          | T
          | {
              detail?: T;
              id?: T;
            };
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-hours_select".
 */
export interface OpeningHoursSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  startDate?: T;
  endDate?: T;
  dailyHours?:
    | T
    | {
        days?: T;
        timeSlots?:
          | T
          | {
              startTime?: T;
              endTime?: T;
              notes?: T;
              id?: T;
            };
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  publishedAt?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        projectHighlights?: T | ProjectHighlightsBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        serviceArea?: T | ServiceAreaBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        machinery?: T | MachineryBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  subtitle?: T;
  ctas?: T;
  image?: T;
  features?:
    | T
    | {
        iconText?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  selectedServices?: T;
  serviceCta?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectHighlightsBlock_select".
 */
export interface ProjectHighlightsBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  buttonText?: T;
  buttonHref?: T;
  highlightedProjects?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  selectedTestimonials?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  galleryCta?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceAreaBlock_select".
 */
export interface ServiceAreaBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  showMap?: T;
  locations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  openingHoursSchedules?: T;
  phoneNumber?: T;
  address?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  template?: T;
  title?: T;
  description?: T;
  selectedFaqs?: T;
  faqCta?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MachineryBlock_select".
 */
export interface MachineryBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  selectedMachinery?: T;
  template?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info".
 */
export interface BusinessInfo {
  id: number;
  /**
   * Polno ime podjetja.
   */
  companyName: string;
  companyAbout: string;
  vatId: string;
  businessId: string;
  registryDate: string;
  location: string;
  phoneNumber: string;
  email: string;
  /**
   * Temna varianta logotipa, ki se uporablja na svetlih ozadjih.
   */
  logo?: (number | null) | Media;
  /**
   * Svetla varianta logotipa, ki se uporablja na temnih ozadjih. Če ni izbrana, se uporabi temna varianta.
   */
  logoLight?: (number | null) | Media;
  facebookUrl?: string | null;
  googleReviewUrl?: string | null;
  /**
   * Dodajte povezave do vaših profilov na platformah za pridobivanje strank.
   */
  leadGenPlatformUrls?:
    | {
        platformName: 'Primerjam.si' | 'Omisli.si' | 'MojMojster.net';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Koordinate lokacije podjetja za prikaz na zemljevidu.
   */
  coordinates: {
    /**
     * Geografska širina lokacije podjetja.
     */
    latitude: number;
    /**
     * Geografska dolžina lokacije podjetja.
     */
    longitude: number;
  };
  /**
   * Radius v metrih, ki označuje območje kjer podjetje nudi svoje storitve.
   */
  serviceRadius: number;
  /**
   * Naslov, ki se prikaže v zavihku brskalnika in rezultatih iskanja.
   */
  metaTitle: string;
  /**
   * Kratek opis strani za rezultate iskanja (približno 155-160 znakov).
   */
  metaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  title?: string | null;
  navItems?:
    | {
        title: string;
        hasChildren?: boolean | null;
        /**
         * Vnesite ciljno pot, npr. /o-nas ali #kontakt.
         */
        href?: string | null;
        /**
         * Dodajte elemente za spustni meni.
         */
        children?:
          | {
              title: string;
              /**
               * Vnesite ciljno pot, npr. /storitve/rezanje-betona.
               */
              href: string;
              /**
               * Kratek opis, ki se prikaže v spustnem meniju.
               */
              description: string;
              /**
               * Izberite ikono, ki se prikaže ob elementu v spustnem meniju.
               */
              icon?: ('Sparkles' | 'Zap' | 'Drop' | 'Hands' | 'Footprints' | 'Paintbrush') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Izberite CTA gumb, ki bo prikazan v navigaciji.
   */
  mainCta?: (number | null) | Cta;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Dodajte povezave do družabnih omrežij, ki se bodo prikazale v nogi strani.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'twitter' | 'tiktok' | 'google';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Besedilo avtorskih pravic, ki bo prikazano na dnu noge. Uporabite {{year}} za dinamično leto.
   */
  copyrightText?: string | null;
  logo?: (number | null) | Media;
  /**
   * Dodajte hitre povezave, ki se bodo prikazale v nogi.
   */
  quickLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  showContactInFooter?: boolean | null;
  showPrivacyLinks?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info_select".
 */
export interface BusinessInfoSelect<T extends boolean = true> {
  companyName?: T;
  companyAbout?: T;
  vatId?: T;
  businessId?: T;
  registryDate?: T;
  location?: T;
  phoneNumber?: T;
  email?: T;
  logo?: T;
  logoLight?: T;
  facebookUrl?: T;
  googleReviewUrl?: T;
  leadGenPlatformUrls?:
    | T
    | {
        platformName?: T;
        url?: T;
        id?: T;
      };
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  serviceRadius?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  title?: T;
  navItems?:
    | T
    | {
        title?: T;
        hasChildren?: T;
        href?: T;
        children?:
          | T
          | {
              title?: T;
              href?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  mainCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  logo?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  showContactInFooter?: T;
  showPrivacyLinks?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}