export const workExamples = (t: any) => [
  {
    id: 1,
    title: t("example1.title"),
    description: t("example1.description"),
    imageUrl: "/gallery/bauher_1.jpg", // Placeholder for future image
    countries: ["SLOVENIA"],
    duration: t("example1.duration"),
  },
  {
    id: 2,
    title: t("example2.title"),
    description: t("example2.description"),
    imageUrl: "/gallery/bauher_2.jpg",
    countries: ["GREAT_BRITAIN"],
    duration: t("example2.duration"),
  },
  {
    id: 3,
    title: t("example3.title"),
    description: t("example3.description"),
    imageUrl: "/gallery/bauher_3.jpg",
    countries: ["SLOVENIA"],
    duration: t("example3.duration"),
  },
  {
    id: 4,
    title: t("example4.title"),
    description: t("example4.description"),
    imageUrl: "/gallery/bauher_4.jpg",
    countries: ["NETHERLANDS"],
    duration: t("example4.duration"),
  },
  {
    id: 5,
    title: t("example5.title"),
    description: t("example5.description"),
    imageUrl: "/gallery/bauher_5.jpg",
    countries: ["GERMANY"],
    duration: t("example5.duration"),
  },
  {
    id: 6,
    title: t("example6.title"),
    description: t("example6.description"),
    imageUrl: "/gallery/bauher_1.jpg",
    countries: ["SLOVENIA", "GERMANY"],
    duration: t("example6.duration"),
  },
  {
    id: 7,
    title: t("example7.title"),
    description: t("example7.description"),
    imageUrl: "/gallery/bauher_2.jpg",
    countries: ["SLOVENIA"],
    duration: t("example7.duration"),
  },
  {
    id: 8,
    title: t("example8.title"),
    description: t("example8.description"),
    imageUrl: "/gallery/bauher_3.jpg",
    countries: [],
    duration: t("example8.duration"),
  },
  {
    id: 9,
    title: t("example9.title"),
    description: t("example9.description"),
    imageUrl: "/gallery/bauher_4.jpg",
    countries: ["SLOVENIA"],
    duration: t("example9.duration"),
  },
];
